"""add certifications to user_profile

Revision ID: ab5510e5af85
Revises: e6196bb3179f
Create Date: 2026-04-15 10:13:04.377516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5510e5af85'
down_revision: Union[str, None] = 'e6196bb3179f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('certifications', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'certifications')
    # ### end Alembic commands ###
