"""Add hourly_rate_snapshot to trainer_sessions

Revision ID: e6196bb3179f
Revises: 9c22503b2916
Create Date: 2026-04-15 09:32:54.865620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6196bb3179f'
down_revision: Union[str, None] = '9c22503b2916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_sessions', sa.Column('hourly_rate_snapshot', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_sessions', 'hourly_rate_snapshot')
    # ### end Alembic commands ###
